pipeline { 
    agent any  
    stages { 
        stage('Build') { 
            steps {  
               bat 'mvn -f web-service/pom.xml clean package'
            }
        }
        stage('Stopping previous application'){
	        steps{
	        	script{
		        	try{	        	
			        	bat 'sh -c "curl -X POST http://localhost:8080/actuator/shutdown"'
		        	}
		        	catch(Exception e){	}
	        	}       
	        }
        }
        stage('Deploying new application'){
        	steps{
        		bat 'sh -c "java -jar target/web-service-0.0.1-SNAPSHOT.jar"'
        	}
        }
    }
}