pipeline { 
    agent any  
    stages { 
        stage('Build') { 
            steps {  
               bat 'mvn -f web-service/pom.xml clean package'
            }
        }
        stage('Stopping previous application'){
	        steps{
	        	script{
		        	try{	        	
			        	bat 'sh -c "curl -X POST localhost:8080/actuator/shutdown"'
		        	}
		        	catch(Exception e){	}
	        	}       
	        }
        }
        
    }
}